import { NextResponse } from 'next/server';
import type { FleetData } from '@/types/fleet';

const fleetData: FleetData = {
  dataReferencia: new Date().toISOString(),
  rebocadores: [
    {
      id: 'rb-01',
      nome: 'SAAM ITABIRA',
      status: 'Em_Manutencao',
      combustivelL: 52000,
      motivoIndisponibilidade: 'Turbina MCP BB + Lona de Freio Guincho de Manobra',
      equipamentos: [
        { id: 'it-mcp-bb', nome: 'MCP BB — Motor Principal Boreste', tipo: 'MCP', status: 'critico', horasAtual: 4200, proximaTroca: 4000, descricao: 'Turbina com perda de pressão — substituição em andamento' },
        { id: 'it-mcp-be', nome: 'MCP BE — Motor Principal Bombordo', tipo: 'MCP', status: 'operacional', horasAtual: 4200, proximaTroca: 4000 },
        { id: 'it-mca-01', nome: 'MCA 01 — Motor Auxiliar / Gerador', tipo: 'MCA', status: 'operacional', horasAtual: 1800, proximaTroca: 2000 },
        { id: 'it-mca-02', nome: 'MCA 02 — Motor Auxiliar / Gerador', tipo: 'MCA', status: 'operacional', horasAtual: 1800, proximaTroca: 2000 },
        { id: 'it-gmc',    nome: 'Guincho de Manobra (Proa)', tipo: 'Guincho', status: 'critico', descricao: 'Lona de freio desgastada — aguardando peça' },
        { id: 'it-asd-bb', nome: 'Propulsor ASD BB', tipo: 'Propulsor ASD', status: 'operacional' },
        { id: 'it-asd-be', nome: 'Propulsor ASD BE', tipo: 'Propulsor ASD', status: 'operacional' },
        { id: 'it-cmp-01', nome: 'Compressor de Ar 01', tipo: 'Compressor', status: 'operacional' },
        { id: 'it-cmp-02', nome: 'Compressor de Ar 02', tipo: 'Compressor', status: 'operacional' },
      ],
    },
    {
      id: 'rb-02',
      nome: 'SAAM LANCELOT',
      status: 'Em_Manutencao',
      combustivelL: 47000,
      motivoIndisponibilidade: 'Preventiva 2.000h MCP BB e BE — troca de óleo, filtros e válvulas termostáticas',
      equipamentos: [
        { id: 'lc-mcp-bb', nome: 'MCP BB — Motor Principal Boreste', tipo: 'MCP', status: 'alerta', horasAtual: 2060, proximaTroca: 2000, descricao: 'Preventiva em execução — óleo cárter, filtros e válvulas termostáticas' },
        { id: 'lc-mcp-be', nome: 'MCP BE — Motor Principal Bombordo', tipo: 'MCP', status: 'alerta', horasAtual: 2060, proximaTroca: 2000, descricao: 'Preventiva em execução — óleo cárter, filtros e válvulas termostáticas' },
        { id: 'lc-mca-01', nome: 'MCA 01 — Motor Auxiliar / Gerador', tipo: 'MCA', status: 'operacional', horasAtual: 980, proximaTroca: 2000 },
        { id: 'lc-mca-02', nome: 'MCA 02 — Motor Auxiliar / Gerador', tipo: 'MCA', status: 'operacional', horasAtual: 980, proximaTroca: 2000 },
        { id: 'lc-gmc',    nome: 'Guincho de Manobra (Proa)', tipo: 'Guincho', status: 'operacional' },
        { id: 'lc-asd-bb', nome: 'Propulsor ASD BB', tipo: 'Propulsor ASD', status: 'operacional' },
        { id: 'lc-asd-be', nome: 'Propulsor ASD BE', tipo: 'Propulsor ASD', status: 'operacional' },
        { id: 'lc-cmp-01', nome: 'Compressor de Ar 01', tipo: 'Compressor', status: 'operacional' },
        { id: 'lc-cmp-02', nome: 'Compressor de Ar 02', tipo: 'Compressor', status: 'operacional' },
      ],
    },
    {
      id: 'rb-03',
      nome: 'SAAM HOLANDA',
      status: 'Disponivel',
      combustivelL: 58000,
      equipamentos: [
        { id: 'ho-mcp-bb', nome: 'MCP BB — Motor Principal Boreste', tipo: 'MCP', status: 'operacional', horasAtual: 1400, proximaTroca: 2000 },
        { id: 'ho-mcp-be', nome: 'MCP BE — Motor Principal Bombordo', tipo: 'MCP', status: 'operacional', horasAtual: 1400, proximaTroca: 2000 },
        { id: 'ho-mca-01', nome: 'MCA 01 — Motor Auxiliar / Gerador', tipo: 'MCA', status: 'operacional', horasAtual: 600, proximaTroca: 2000 },
        { id: 'ho-mca-02', nome: 'MCA 02 — Motor Auxiliar / Gerador', tipo: 'MCA', status: 'operacional', horasAtual: 600, proximaTroca: 2000 },
        { id: 'ho-gmc',    nome: 'Guincho de Manobra (Proa)', tipo: 'Guincho', status: 'alerta', descricao: 'Mangueira hidráulica com microtrinca — monitoramento' },
        { id: 'ho-asd-bb', nome: 'Propulsor ASD BB', tipo: 'Propulsor ASD', status: 'operacional' },
        { id: 'ho-asd-be', nome: 'Propulsor ASD BE', tipo: 'Propulsor ASD', status: 'operacional' },
        { id: 'ho-cmp-01', nome: 'Compressor de Ar 01', tipo: 'Compressor', status: 'operacional' },
        { id: 'ho-cmp-02', nome: 'Compressor de Ar 02', tipo: 'Compressor', status: 'operacional' },
      ],
    },
    {
      id: 'rb-04',
      nome: 'SAAM ARIES',
      status: 'Disponivel',
      combustivelL: 28000,
      equipamentos: [
        { id: 'ar-mcp-bb', nome: 'MCP BB — Motor Principal Boreste', tipo: 'MCP', status: 'operacional', horasAtual: 850, proximaTroca: 2000 },
        { id: 'ar-mcp-be', nome: 'MCP BE — Motor Principal Bombordo', tipo: 'MCP', status: 'operacional', horasAtual: 850, proximaTroca: 2000 },
        { id: 'ar-mca-01', nome: 'MCA 01 — Motor Auxiliar / Gerador', tipo: 'MCA', status: 'operacional', horasAtual: 400, proximaTroca: 2000 },
        { id: 'ar-mca-02', nome: 'MCA 02 — Motor Auxiliar / Gerador', tipo: 'MCA', status: 'operacional', horasAtual: 400, proximaTroca: 2000 },
        { id: 'ar-gmc',    nome: 'Guincho de Manobra (Proa)', tipo: 'Guincho', status: 'operacional' },
        { id: 'ar-asd-bb', nome: 'Propulsor ASD BB', tipo: 'Propulsor ASD', status: 'operacional' },
        { id: 'ar-asd-be', nome: 'Propulsor ASD BE', tipo: 'Propulsor ASD', status: 'operacional' },
        { id: 'ar-cmp-01', nome: 'Compressor de Ar 01', tipo: 'Compressor', status: 'alerta', descricao: 'Correia com desgaste — troca no próximo atracado' },
        { id: 'ar-cmp-02', nome: 'Compressor de Ar 02', tipo: 'Compressor', status: 'operacional' },
      ],
    },
    {
      id: 'rb-05',
      nome: 'SAAM CHILE',
      status: 'Disponivel',
      combustivelL: 60000,
      equipamentos: [
        { id: 'ch-mcp-bb', nome: 'MCP BB — Motor Principal Boreste', tipo: 'MCP', status: 'operacional', horasAtual: 550, proximaTroca: 2000 },
        { id: 'ch-mcp-be', nome: 'MCP BE — Motor Principal Bombordo', tipo: 'MCP', status: 'operacional', horasAtual: 550, proximaTroca: 2000 },
        { id: 'ch-mca-01', nome: 'MCA 01 — Motor Auxiliar / Gerador', tipo: 'MCA', status: 'operacional', horasAtual: 300, proximaTroca: 2000 },
        { id: 'ch-mca-02', nome: 'MCA 02 — Motor Auxiliar / Gerador', tipo: 'MCA', status: 'operacional', horasAtual: 300, proximaTroca: 2000 },
        { id: 'ch-gmc',    nome: 'Guincho de Manobra (Proa)', tipo: 'Guincho', status: 'operacional' },
        { id: 'ch-asd-bb', nome: 'Propulsor ASD BB', tipo: 'Propulsor ASD', status: 'operacional' },
        { id: 'ch-asd-be', nome: 'Propulsor ASD BE', tipo: 'Propulsor ASD', status: 'operacional' },
        { id: 'ch-cmp-01', nome: 'Compressor de Ar 01', tipo: 'Compressor', status: 'operacional' },
        { id: 'ch-cmp-02', nome: 'Compressor de Ar 02', tipo: 'Compressor', status: 'operacional' },
      ],
    },
    {
      id: 'rb-06',
      nome: 'SAAM ARTHUR',
      status: 'Disponivel',
      combustivelL: 31000,
      equipamentos: [
        { id: 'au-mcp-bb', nome: 'MCP BB — Motor Principal Boreste', tipo: 'MCP', status: 'operacional', horasAtual: 1100, proximaTroca: 2000 },
        { id: 'au-mcp-be', nome: 'MCP BE — Motor Principal Bombordo', tipo: 'MCP', status: 'operacional', horasAtual: 1100, proximaTroca: 2000 },
        { id: 'au-mca-01', nome: 'MCA 01 — Motor Auxiliar / Gerador', tipo: 'MCA', status: 'alerta', horasAtual: 1850, proximaTroca: 2000, descricao: 'AVR com leitura instável — aguardando técnico CAT' },
        { id: 'au-mca-02', nome: 'MCA 02 — Motor Auxiliar / Gerador', tipo: 'MCA', status: 'operacional', horasAtual: 1850, proximaTroca: 2000 },
        { id: 'au-gmc',    nome: 'Guincho de Manobra (Proa)', tipo: 'Guincho', status: 'operacional' },
        { id: 'au-asd-bb', nome: 'Propulsor ASD BB', tipo: 'Propulsor ASD', status: 'operacional' },
        { id: 'au-asd-be', nome: 'Propulsor ASD BE', tipo: 'Propulsor ASD', status: 'operacional' },
        { id: 'au-cmp-01', nome: 'Compressor de Ar 01', tipo: 'Compressor', status: 'operacional' },
        { id: 'au-cmp-02', nome: 'Compressor de Ar 02', tipo: 'Compressor', status: 'operacional' },
      ],
    },
  ],
  estoque: {
    diesel_L: 42000,
    oleo_L: 3200,
    autonomiaDias: 12,
  },
  resumo: {
    totalRebocadores: 6,
    disponiveis: 4,
    emManutencao: 2,
    emOperacao: 0,
    custoTotalPrevisto: 87500,
  },
};

export async function GET() {
  return NextResponse.json(fleetData);
}
